import "./globals.css";
import type { Metadata } from "next";
import RecoilRootWrapper from "../RecoilRootWrapper";
import NextAuthProvider from "@/Layouts/NextAuthProvider";
export const metadata: Metadata = {
  title: "preplord",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <RecoilRootWrapper>{children}</RecoilRootWrapper>
        </NextAuthProvider>
      </body>
    </html>
  );
}
