export const cities = [
  { name: "Mumbai" },
  { name: "Delhi" },
  { name: "Bangalore" },
  { name: "Hyderabad" },
  { name: "Chennai" },
  { name: "Kolkata" },
  { name: "Ahmedabad" },
  { name: "Pune" },
  { name: "Surat" },
  { name: "Jaipur" },
  { name: "Lucknow" },
  { name: "Kanpur" },
  { name: "Nagpur" },
  { name: "Indore" },
  { name: "Thane" },
  { name: "Bhopal" },
  { name: "Visakhapatnam" },
  { name: "Pimpri-Chinchwad" },
  { name: "Patna" },
  { name: "Vadodara" },
  { name: "Ghaziabad" },
  { name: "Ludhiana" },
  { name: "Agra" },
  { name: "Nashik" },
  { name: "Faridabad" },
  { name: "Meerut" },
  { name: "Rajkot" },
  { name: "Kalyan-Dombivali" },
  { name: "Vasai-Virar" },
  { name: "Varanasi" },
  { name: "Srinagar" },
  { name: "Aurangabad" },
  { name: "Dhanbad" },
  { name: "Amritsar" },
  { name: "Navi Mumbai" },
  { name: "Allahabad" },
  { name: "Ranchi" },
  { name: "Howrah" },
  { name: "Coimbatore" },
  { name: "Jabalpur" },
  { name: "Gwalior" },
  { name: "Vijayawada" },
  { name: "Jodhpur" },
  // ... add more major cities
];

export const mock_types = [{ value: "Practice" }, { value: "Full Mock" }];
